/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import clases.UdpClient;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static projeto.PrincipalPage.deleteWord;

/**
 *
 * @author julio
 */
public class Login extends javax.swing.JFrame {
    
    static private String email;
     
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        EmailTag = new javax.swing.JLabel();
        PasswordTag = new javax.swing.JLabel();
        TextFieldEmail1 = new javax.swing.JTextField();
        buttonLoginChangeSite = new javax.swing.JButton();
        PasswordFieldPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        EmailTag1 = new javax.swing.JLabel();
        EmailTag2 = new javax.swing.JLabel();
        UserNameTag2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dumbbell.PNG"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setName("Dumbbell"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleName("Dumbbell");
        jLabel2.getAccessibleContext().setAccessibleDescription("Dumbbell");

        buttonLogin.setBackground(new java.awt.Color(79, 79, 79));
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("LOGIN");
        buttonLogin.setToolTipText("");
        buttonLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonLogin.setBorderPainted(false);
        buttonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 480, 40));

        EmailTag.setText("Email");
        getContentPane().add(EmailTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        PasswordTag.setText("Password");
        getContentPane().add(PasswordTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        TextFieldEmail1.setBackground(new java.awt.Color(234, 234, 234));
        getContentPane().add(TextFieldEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 480, 40));

        buttonLoginChangeSite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginNegrita.PNG"))); // NOI18N
        buttonLoginChangeSite.setBorder(null);
        buttonLoginChangeSite.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(buttonLoginChangeSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 70, 30));

        PasswordFieldPassword.setBackground(new java.awt.Color(234, 234, 234));
        getContentPane().add(PasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 480, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White Wallpaper.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 79, 79)));
        jLabel1.setDoubleBuffered(true);
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 760));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        EmailTag1.setText("Email");
        getContentPane().add(EmailTag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        EmailTag2.setText("Email");
        getContentPane().add(EmailTag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        UserNameTag2.setText("Username");
        getContentPane().add(UserNameTag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        String email = "", pwd = "";
        email = TextFieldEmail1.getText();
        pwd = String.valueOf(PasswordFieldPassword.getPassword());
        
        UdpClient client = new UdpClient(1,email,pwd);
        String msg = client.initClient();
        
        System.out.println(msg);
        if(msg.contains("true")){
            
                String accum = "",accum2 = "", word = "", nameTable = "";
                String tipoUtilizador = "",nome = "";
                int cont = 1;
                    for(int i = 0; i < msg.length(); i++){
                        char c = msg.charAt(i); 
                            if(c == '#' || c == '%'){
                                accum2 += c;
                                accum += c;
                                if("#%#".equals(accum2)){
                                    word = deleteWord(accum,accum2);
                                    System.out.println("Ver accum:------");
                                    System.out.println(word);
                                    switch(cont){
                                    case 1:
                                        nome = word;
                                        break;
                                    case 2:
                                        tipoUtilizador = word;
                                        break;
                                    }
                                    accum2 = "";
                                    accum = "";
                                    cont++;
                                }
                            } else {
                                accum += c;
                            }
                    }
                    
                if("1".equals(tipoUtilizador)){
                    this.email = TextFieldEmail1.getText();
                    JOptionPane.showMessageDialog(null, "Bem-vindo");
                    PrincipalPage page = new PrincipalPage(this.email); 
                    page.setVisible(true);
                    dispose();
                } else {
                    this.email = TextFieldEmail1.getText();
                    JOptionPane.showMessageDialog(null, "Bem-vindo");
                    JFrame frame = new JFrame ("Manager Page");
                    final JFXPanel fxPanel = new JFXPanel ();
                    frame.add (fxPanel);
                    frame.setSize (1200, 750);
                    frame.setVisible(true);
                    frame.setDefaultCloseOperation (JFrame.DISPOSE_ON_CLOSE);
                    frame.setLocationRelativeTo(null);
                    frame.setResizable(false);
                    dispose();
                    Platform.runLater (new Runnable () {
                        @Override
                        public void run() {
                            initFX(fxPanel);
                        }
                   });
                }
        } else {
            JOptionPane.showMessageDialog(null, "Dados inválidos");
            this.clean();
        }
    }//GEN-LAST:event_buttonLoginActionPerformed
    
    private static void initFX(JFXPanel fxPanel) {
        // This method is invoked on the JavaFX thread
        Scene scene = createScene();
        fxPanel.setScene(scene);
    }
    
    private static Scene createScene() {
        Button btn = new Button();
        HBox hbox = new HBox();
        
        Image imgLogo = new Image("./Images/dumbbell.PNG");
        ImageView loadImg = new ImageView(imgLogo);
        
        String emailCreateScene = Login.setParameters(Login.email);
        
        Label name = new Label();
        name.setText(emailCreateScene);
        Button btnPerfil = new Button();
        
        VBox vbox = new VBox();
        vbox.setTranslateY(45);
        vbox.setTranslateX(10);
        vbox.getChildren().add(name);
        vbox.getChildren().add(btnPerfil);
        
        btn.setText("Procurar Cliente");
        btn.setTranslateY(45);
        btn.setTranslateX(20);
        btn.setOnAction(new EventHandler<ActionEvent>() {
            
            @Override
            public void handle(ActionEvent event) {
                ProcurarClienteFX page = new ProcurarClienteFX();
                Stage stage = new Stage();
                page.start(stage);
            }
        });
        
        btnPerfil.setText("Perfil");
        
        btnPerfil.setOnAction(new EventHandler<ActionEvent>() {
            
            @Override
            public void handle(ActionEvent event) {
                PerfilManager page = new PerfilManager(Login.email);
                page.setVisible(true);
            }
        });
        
        hbox.getChildren().add(loadImg);        
        hbox.getChildren().add(vbox);
        hbox.getChildren().add(btn);
        
        Group  root  =  new  Group();
        Scene  scene  =  new  Scene(root, Color.WHITE);
        Text  text  =  new  Text();
        
        root.getChildren().add(hbox);
        
        root.setStyle("-fx-background-color: white;");

        return (scene);
    }
    
    static public String setParameters(String email){
        UdpClient client = new UdpClient("Principal Page",email);
        String msg = client.initClient();
        System.out.println("Este es el msg : " + msg);
        
        String accum = "",accum2 = "", word = "", nameTable = "";
        String nome = "";
        int cont = 1;
            for(int i = 0; i < msg.length(); i++){
                char c = msg.charAt(i); 
                    if(c == '#' || c == '%'){
                        accum2 += c;
                        accum += c;
                        if("#%#".equals(accum2)){
                            word = deleteWord(accum,accum2);
                            System.out.println("Ver accum:------");
                            System.out.println(word);
                            switch(cont){
                            case 1:
                                nome = word;
                                break;
                            }
                            accum2 = "";
                            accum = "";
                            cont++;
                        }
                    } else {
                        accum += c;
                    }
            }
            
        System.out.println("this es the name : " + nome);
        return nome;
    }
    
    private void clean(){
        TextFieldEmail1.setText(null);
        PasswordFieldPassword.setText(null);
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailTag;
    private javax.swing.JLabel EmailTag1;
    private javax.swing.JLabel EmailTag2;
    private javax.swing.JPasswordField PasswordFieldPassword;
    private javax.swing.JLabel PasswordTag;
    private javax.swing.JTextField TextFieldEmail1;
    private javax.swing.JLabel UserNameTag2;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonLoginChangeSite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
