/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import clases.UdpClient;
import static java.lang.Integer.parseInt;
import static projeto.PrincipalPage.deleteWord;

/**
 *
 * @author julio
 */
public class ManagerPage extends javax.swing.JFrame {

    private String email;
    
    public ManagerPage(String email) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        this.email = email;
        this.setParameters(email);
    }
    public ManagerPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        nameUser = new javax.swing.JLabel();
        buttonPerfil = new javax.swing.JButton();
        buttonProcurarCliente = new javax.swing.JButton();
        wallpaperBig = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dumbbell.PNG"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        nameUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameUser.setForeground(new java.awt.Color(112, 112, 112));
        nameUser.setText("Manager name");
        getContentPane().add(nameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        buttonPerfil.setBackground(new java.awt.Color(255, 255, 255));
        buttonPerfil.setText("Perfil");
        buttonPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPerfil.setFocusPainted(false);
        buttonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        buttonProcurarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonProcurarCliente.PNG"))); // NOI18N
        buttonProcurarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonProcurarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcurarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonProcurarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 190, 40));

        wallpaperBig.setBackground(new java.awt.Color(79, 79, 79));
        wallpaperBig.setForeground(new java.awt.Color(255, 255, 255));
        wallpaperBig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperBig.png"))); // NOI18N
        wallpaperBig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 79, 79)));
        getContentPane().add(wallpaperBig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setParameters(String email){
        UdpClient client = new UdpClient("Principal Page",email);
        String msg = client.initClient();
        System.out.println("Este es el msg : " + msg);
        
        String accum = "",accum2 = "", word = "", nameTable = "";
        String nome = "";
        int cont = 1;
            for(int i = 0; i < msg.length(); i++){
                char c = msg.charAt(i); 
                    if(c == '#' || c == '%'){
                        accum2 += c;
                        accum += c;
                        if("#%#".equals(accum2)){
                            word = deleteWord(accum,accum2);
                            System.out.println("Ver accum:------");
                            System.out.println(word);
                            switch(cont){
                            case 1:
                                nome = word;
                                break;
                            }
                            accum2 = "";
                            accum = "";
                            cont++;
                        }
                    } else {
                        accum += c;
                    }
            }
            //System.out.println("email : " + nome);
            //System.out.println("pass : " + cartao);
            //System.out.println("pass : " + credito);
            
        System.out.println("this es the name : " + nome);
        nameUser.setText(nome);
    }
    
    private void buttonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerfilActionPerformed
        PerfilManager page = new PerfilManager(email);
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonPerfilActionPerformed

    private void buttonProcurarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcurarClienteActionPerformed
        ProcurarCliente page = new ProcurarCliente();
        page.setVisible(true);
    }//GEN-LAST:event_buttonProcurarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton buttonPerfil;
    private javax.swing.JButton buttonProcurarCliente;
    private javax.swing.JLabel nameUser;
    private javax.swing.JLabel wallpaperBig;
    // End of variables declaration//GEN-END:variables
}
