/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import clases.UdpClient;
import static java.lang.Double.parseDouble;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static projeto.PrincipalPage.deleteWord;

/**
 *
 * @author julio
 */
public class PagarMesalidade extends javax.swing.JFrame {

    private String email;
    private String Pmes;
    private String Pano;
    
    public PagarMesalidade(String email) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        this.email = email;
    
        this.setParameters(email);
    }
    
    public PagarMesalidade() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        monthAndYear = new javax.swing.JLabel();
        RecarragarCartaoTag = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EmailTag1 = new javax.swing.JLabel();
        EmailTag2 = new javax.swing.JLabel();
        UserNameTag2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonPagar.setBackground(new java.awt.Color(79, 79, 79));
        buttonPagar.setForeground(new java.awt.Color(255, 255, 255));
        buttonPagar.setText("PAGAR");
        buttonPagar.setToolTipText("");
        buttonPagar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonPagar.setBorderPainted(false);
        buttonPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPagar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 480, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("29,99€");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 236, 80, 30));

        monthAndYear.setText("mes - 1");
        getContentPane().add(monthAndYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        RecarragarCartaoTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RecarragarCartaoTag.setForeground(new java.awt.Color(112, 112, 112));
        RecarragarCartaoTag.setText("Pagar Mensalidade");
        getContentPane().add(RecarragarCartaoTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White Wallpaper.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 79, 79)));
        jLabel1.setDoubleBuffered(true);
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 760));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        EmailTag1.setText("Email");
        getContentPane().add(EmailTag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        EmailTag2.setText("Email");
        getContentPane().add(EmailTag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        UserNameTag2.setText("Username");
        getContentPane().add(UserNameTag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setParameters(String email){
        UdpClient client = new UdpClient("Verificar Mensalidade",email);
        String msg = client.initClient();
        System.out.println("Este es el msg en Verificar Mensalidade: " + msg);
        
        String accumt = "",accum22 = "", word2 = "";
        String mes = "", ano = "";
        int cont2 = 1;
            for(int i = 0; i < msg.length(); i++){
                char c2 = msg.charAt(i); 
                    if(c2 == '#' || c2 == '%'){
                        accum22 += c2;
                        accumt += c2;
                        if("#%#".equals(accum22)){
                            word2 = deleteWord(accumt,accum22);
                            System.out.println("Ver accum:------");
                            System.out.println(word2);
                            switch(cont2){
                            case 1:
                                mes = word2;
                                break;
                            case 2:
                                ano = word2;
                                break;
                            }
                            accum22 = "";
                            accumt = "";
                            cont2++;
                        }
                    } else {
                        accumt += c2;
                    }
            }
            
            Pmes = mes;
            Pano = ano;
            monthAndYear.setText(mes + " - " + ano);
            
    }
    
    private void buttonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPagarActionPerformed
        UdpClient client = new UdpClient("Pagar Mensalidade",email,Pmes,Pano);
        String msg = client.initClient();
        System.out.println("Este es el msg en Pagar Mensalidade: " + msg);
        
        
        if(msg.contains("Pagamento efectuado")){
            JOptionPane.showMessageDialog(null, "Pagamento efectuado");
            PrincipalPage page = new PrincipalPage(this.email); 
            page.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Erro no pagamento");
            PrincipalPage page = new PrincipalPage(this.email); 
            page.setVisible(true);
            dispose();
        }

        
    }//GEN-LAST:event_buttonPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarMesalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarMesalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarMesalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarMesalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagarMesalidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailTag1;
    private javax.swing.JLabel EmailTag2;
    private javax.swing.JLabel RecarragarCartaoTag;
    private javax.swing.JLabel UserNameTag2;
    private javax.swing.JButton buttonPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel monthAndYear;
    // End of variables declaration//GEN-END:variables
}
