/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import clases.UdpClient;
import static java.lang.Integer.parseInt;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author julio
 */
public class PrincipalPage extends javax.swing.JFrame {

    private String email;
    private int cartao;
    
    public PrincipalPage(String email) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.email = email;
        this.setParameters(email);
    }
    
    public PrincipalPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        nameUser = new javax.swing.JLabel();
        buttonPerfil = new javax.swing.JButton();
        buttonRecarregarCredito = new javax.swing.JButton();
        buttonMovimentosCartao = new javax.swing.JButton();
        NumeroCartaoTag = new javax.swing.JLabel();
        NumeroCartao = new javax.swing.JLabel();
        CreditoTag = new javax.swing.JLabel();
        jLabelCredito = new javax.swing.JLabel();
        buttonPagarMensalidade = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHours = new javax.swing.JTable();
        wallpaperBig = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dumbbell.PNG"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        nameUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameUser.setForeground(new java.awt.Color(112, 112, 112));
        nameUser.setText("Julio Cesar Daal De Sousa");
        getContentPane().add(nameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        buttonPerfil.setBackground(new java.awt.Color(255, 255, 255));
        buttonPerfil.setText("Perfil");
        buttonPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPerfil.setFocusPainted(false);
        buttonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        buttonRecarregarCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonRecarregarCredito.PNG"))); // NOI18N
        buttonRecarregarCredito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonRecarregarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRecarregarCreditoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRecarregarCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 190, 40));

        buttonMovimentosCartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonMovimentosCartao.PNG"))); // NOI18N
        buttonMovimentosCartao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMovimentosCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMovimentosCartaoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMovimentosCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 190, 40));

        NumeroCartaoTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NumeroCartaoTag.setForeground(new java.awt.Color(112, 112, 112));
        NumeroCartaoTag.setText("Nº Cartão:");
        getContentPane().add(NumeroCartaoTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        NumeroCartao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NumeroCartao.setForeground(new java.awt.Color(112, 112, 112));
        NumeroCartao.setText("190208014");
        getContentPane().add(NumeroCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        CreditoTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CreditoTag.setForeground(new java.awt.Color(112, 112, 112));
        CreditoTag.setText("Credito (€):");
        getContentPane().add(CreditoTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabelCredito.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCredito.setForeground(new java.awt.Color(112, 112, 112));
        jLabelCredito.setText("50");
        getContentPane().add(jLabelCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        buttonPagarMensalidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttonPagarMensalidade.PNG"))); // NOI18N
        buttonPagarMensalidade.setContentAreaFilled(false);
        buttonPagarMensalidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPagarMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagarMensalidadeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPagarMensalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 180, 40));

        tableHours.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableHours.setForeground(new java.awt.Color(112, 112, 112));
        tableHours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Data", "Entrada/Saída"
            }
        ));
        tableHours.setGridColor(new java.awt.Color(255, 255, 255));
        tableHours.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(tableHours);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 850, 520));

        wallpaperBig.setBackground(new java.awt.Color(79, 79, 79));
        wallpaperBig.setForeground(new java.awt.Color(255, 255, 255));
        wallpaperBig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperBig.png"))); // NOI18N
        wallpaperBig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 79, 79)));
        wallpaperBig.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(wallpaperBig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRecarregarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRecarregarCreditoActionPerformed
        RecarregarCartao page = new RecarregarCartao(this.email,this.cartao);
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonRecarregarCreditoActionPerformed

    private void buttonMovimentosCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMovimentosCartaoActionPerformed
        MovimentoCartao page = new MovimentoCartao(this.email);
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonMovimentosCartaoActionPerformed

    private void buttonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerfilActionPerformed
        Perfil page = new Perfil(this.email);
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonPerfilActionPerformed

    private void buttonPagarMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPagarMensalidadeActionPerformed
        PagarMesalidade page = new PagarMesalidade(this.email);
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonPagarMensalidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static String  deleteWord(String sentence,String word) {
        if(sentence.contains(word))
            return sentence.replaceAll(word, "");
        return sentence;
    }
    
    public void setParameters(String email){
        UdpClient client = new UdpClient("Principal Page",email);
        String msg = client.initClient();
        System.out.println("Este es el msg : " + msg);
        
        String accum = "",accum2 = "", word = "", nameTable = "";
        String nome = "", cartao = "", credito = "";
        int cont = 1;
            for(int i = 0; i < msg.length(); i++){
                char c = msg.charAt(i); 
                    if(c == '#' || c == '%'){
                        accum2 += c;
                        accum += c;
                        if("#%#".equals(accum2)){
                            word = deleteWord(accum,accum2);
                            System.out.println("Ver accum:------");
                            System.out.println(word);
                            switch(cont){
                            case 1:
                                nome = word;
                                break;
                            case 2:
                                cartao = word;
                                break;
                            case 3:
                                credito = word;
                                break;
                            }
                            accum2 = "";
                            accum = "";
                            cont++;
                        }
                    } else {
                        accum += c;
                    }
            }
            //System.out.println("email : " + nome);
            //System.out.println("pass : " + cartao);
            //System.out.println("pass : " + credito);
            
        
        nameUser.setText(nome);
        this.cartao = parseInt(cartao);
        
        UdpClient client3 = new UdpClient("Catch idUtilizador",email);
        String msg3 = client3.initClient();
        System.out.println("Este es el msg : " + msg3);
        
        String accum3 = "",accum23 = "", word3 = "", nameTable3 = "";
        String ids = "";
        int cont3 = 1;
            for(int i3 = 0; i3 < msg3.length(); i3++){
                System.out.println("El char : " + msg3.charAt(i3));
                char c3 = msg3.charAt(i3); 
                    if(c3 == '#' || c3 == '%'){
                        accum23 += c3;
                        accum3 += c3;
                        if("#%#".equals(accum23)){
                            word3 = deleteWord(accum3,accum23);
                            System.out.println("Ver accum:------");
                            System.out.println(word3);
                            switch(cont3){
                            case 1:
                                ids = word3;
                                break;
                            }
                            accum23 = "";
                            accum3 = "";
                            cont3++;
                        }
                    } else {
                        accum3 += c3;
                    }
            }
        System.out.println("Este es el this.email : " + this.email);
        System.out.println("Este es el ids : " + ids);
        NumeroCartao.setText(ids);
        
        
        
        jLabelCredito.setText(credito);
        
        //Adicionar dados tabela
        UdpClient client2 = new UdpClient("Table Principal Page",email);
        String msg2 = client2.initClient();
        System.out.println("Este es el msg AQUI: " + msg2);
        
        String accumt = "",accum22 = "", word2 = "";
        String hora = "", dataTreino = "", entrada = "";
        int cont2 = 1;
        
        DefaultTableModel tabelas = (DefaultTableModel) tableHours.getModel();
        
            for(int i = 0; i < msg2.length(); i++){
                char c2 = msg2.charAt(i); 
                    if(c2 == '#' || c2 == '%'){
                        accum22 += c2;
                        accumt += c2;
                        if("#%#".equals(accum22)){
                            word2 = deleteWord(accumt,accum22);
                            System.out.println("Ver accum:------");
                            System.out.println(word2);
                            switch(cont2){
                            case 1:
                                hora = word2;
                                break;
                            case 2:
                                dataTreino = word2;
                                break;
                            case 3:
                                entrada = word2;
                                break;
                            }
                            accum22 = "";
                            accumt = "";
                            if(cont2 == 3){
                                Object[] dados = {hora,dataTreino,entrada};
                                tabelas.addRow(dados);
                                cont2 = 1;
                            } else {
                                cont2++;
                            }
                        }
                    } else {
                        accumt += c2;
                    }
            }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreditoTag;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NumeroCartao;
    private javax.swing.JLabel NumeroCartaoTag;
    private javax.swing.JButton buttonMovimentosCartao;
    private javax.swing.JButton buttonPagarMensalidade;
    private javax.swing.JButton buttonPerfil;
    private javax.swing.JButton buttonRecarregarCredito;
    private javax.swing.JLabel jLabelCredito;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameUser;
    private javax.swing.JTable tableHours;
    private javax.swing.JLabel wallpaperBig;
    // End of variables declaration//GEN-END:variables
}
